Fix Jest config for MSW + axios compatibility (#77)
## Description

Jest tests were failing with the error below on freshly created Expo app
using the CLI.

```
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { LensList } from "./lens-list.mjs";
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import { setupServer } from 'msw/node';
        | ^
      2 |
      3 | /**
      4 |  * MSW server for mocking network requests

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (node_modules/msw/src/core/experimental/define-network.ts:2:47)
      at Object.<anonymous> (node_modules/msw/src/node/setup-server.ts:9:8)
      at Object.require (src/test/server.ts:1:1)
      at Object.require (jest.setup.js:4:1)
```

Jest fixes were made to the Expo app built from the boilerplate Belt
template and ported to the CLI as well so that tests for new apps don't
break.

## Related links
- https://mswjs.io/docs/integrations/react-native/#prerequisites
- https://github.com/mswjs/msw/issues/2698
- https://github.com/mswjs/msw/issues/170